[build]
  publish = "public"
  command = "npx hugo-extended@0.118.2 --gc --minify"

[build.environment]
  HUGO_ENV = "production"
  TZ = "UTC"

[context.production.environment]
  HUGO_VERSION = "0.118.2"
  HUGO_EXTENDED = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.118.2"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.118.2"

[functions]
# default build settings
node_bundler = "esbuild"

# ðŸ‘‡ tell Netlify to use Deno for this function
[[functions]]
path = "netlify/functions/counter.js"
runtime = "deno"
deno_import_map = "import_map.json"


