[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.118.2"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  TZ = "UTC"
  NETLIFY_IMAGE  = "ubuntu-24.04"

[context.production.environment]
  HUGO_VERSION = "0.118.2"
  HUGO_EXTENDED = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.118.2"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.118.2"
