[context.deploy-preview.environment]
  HUGO_VERSION = "0.51"

[context.production.environment]
  HUGO_VERSION = "0.51"

[context.branch-deploy.environment] 
  HUGO_VERSION = "0.51"

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"
  [build.environment]
    HUGO_VERSION = "0.51"