[build]
  publish = "public"
  command = "npx hugo-extended@0.118.2 --gc --minify"

[build.environment]
  HUGO_ENV = "production"
  TZ = "UTC"

[context.production.environment]
  HUGO_VERSION = "0.118.2"
  HUGO_EXTENDED = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.118.2"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.118.2"
  
[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' data:"
